### PR TITLE
changed info near components

### PR DESCRIPTION
**Pull request by JonMurphy**
and I missed a "hass". 

So when we add the Weblink and Weather Underground and Worldclock, what changes?  Does the Home Assistant Home "States" webpage change or something else?

### CODE REVIEW

**Comment by bassclarinetl2** [comment]
yep.  not only should a new entity show up under the < > section from the
sidebar.  but the data should appear in the main ui.

**Comment by JonMurphy** [comment]
Can you do a image for each one?  (or them all together).  I am going to try and add clocks since I don't quite understand what I might see that is different

**Comment by bassclarinetl2** [comment]
sure.  though I will hafta spin up a new install.  *(thats some of the
reason that there are only cli pics)

**Comment by JonMurphy** [comment]
OK, here is some of the confusion for me!

I added the [Worldclock](https://home-assistant.io/components/sensor.worldclock/) just as the example states.  And it seems like there is an error.  I tried to run `hass --script check_config` and that returns the error.

```
pi@raspberrypi:~ $ hass --script check_config
-bash: hass: command not found

pi@raspberrypi:~ $ sudo su -s /bin/bash homeassistant
homeassistant@raspberrypi:/home/pi $ hass --script check_config
bash: hass: command not found

homeassistant@raspberrypi:/home/pi $ cd .homeassistant
homeassistant@raspberrypi:/home/pi/.homeassistant $ hass --script check_config
bash: hass: command not found
```
So for some odd reason the script check doesn't like bash. So I ran this: `/srv/homeassistant/homeassistant_venv/bin/hass --script check_config`

```
homeassistant@raspberrypi:~/.homeassistant $ /srv/homeassistant/homeassistant_venv/bin/hass --script check_config
INFO:homeassistant.util.package:Attempting install of colorlog>2.1,<3
Testing configuration at /home/homeassistant/.homeassistant
17-02-03 17:21:33 ERROR (Thread-1) [homeassistant.util.yaml] duplicate key: "sensor"
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 47, column 0
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 50, column 0

```
And apparently the duplicate "sensor:" is bad.  so I removed the duplicate "sensor:".

```
homeassistant@raspberrypi:/home/pi/.homeassistant $ /srv/homeassistant/homeassistant_venv/bin/hass --script check_config
Testing configuration at /home/homeassistant/.homeassistant
17-02-03 17:44:55 ERROR (Thread-1) [homeassistant.util.yaml] mapping values are not allowed here
  in "/home/homeassistant/.homeassistant/configuration.yaml", line 51, column 14
```

SO - the two questions are:

1. why can I not run `hass --script check_config` without the full path to `hass`
2. and - why does adding this:
screen shot 2017-02-03 at 5 51 29 pm

cause this error --> **mapping values are not allowed here**

**Comment by bassclarinetl2** [comment]
looks like they added some default components after i drafted the guide.
 under sensor:  add a - (thats a dash_ infront of both lines.)  the reason
for the need to include the whole path (/srv/homeassistant etc) is because
the hass binary (program if you prefer) isn't in the global path for the pi
(read: executable everywhere) so you have to either specify the whole path
or cd into /srv/homeassistant/homeassistant_venv/bin and then run the
command

**Comment by bassclarinetl2** [comment]
made some changes and added pics.

**Comment by JonMurphy** [comment]
same error for the same line.  It does not like this line:
`        time_zone: America/New_York`

screen shot 2017-02-03 at 6 56 30 pm

Is a dash needed in front of "time_zone:"?

**Comment by bassclarinetl2** [comment]
move `time_zone` back two spaces.

**Comment by bassclarinetl2** [comment]
lets try that while again;

like this:

- platform: worldclock
  time_zone: America/New_York

**Comment by JonMurphy** [comment]
AAAAAHHHHHHhhhhhhhhh!  Spaces mater that much?!?

Need a NOOB chapter just for nuances!

PS - it worked!

**Comment by JonMurphy** [comment]
Here is a pic from an iPhone for the Worldclock.  (feel free to trash if you prefer something else)

img_2426

**Pull request merged**
